import React from 'react';
import { StyleSheet, Text } from 'react-native';

class Initial extends React.Component {

  render() {
    return ([
        <Text>HIKJBKJBSFKJBSDKFJBSDFBSDFUBSDFOUSBDFOUSDFBSDUFSDOFSOUFSOUFOUSFBSUOFSOUF</Text>,
        <Text>HIKJBKJBSFKJBSDKFJBSDFBSDFUBSDFOUSBDFOUSDFBSDUFSDOFSOUFSOUFOUSFBSUOFSOUF</Text>,
        <Text>HIKJBKJBSFKJBSDKFJBSDFBSDFUBSDFOUSBDFOUSDFBSDUFSDOFSOUFSOUFOUSFBSUOFSOUF</Text>,
        <Text>HIKJBKJBSFKJBSDKFJBSDFBSDFUBSDFOUSBDFOUSDFBSDUFSDOFSOUFSOUFOUSFBSUOFSOUF</Text>,
        <Text>HIKJBKJBSFKJBSDKFJBSDFBSDFUBSDFOUSBDFOUSDFBSDUFSDOFSOUFSOUFOUSFBSUOFSOUF</Text>
    ]
    );
  }
}


const styles = StyleSheet.create({

});

export default Initial